---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-ns-labels
spec:
  background: false
  rules:
    - name: add-label
      match:
        any:
          - resources:
              kinds:
                - Namespace
      exclude:
        any:
          - clusterRoles:
              - cluster-admin
      mutate:
        patchStrategicMerge:
          metadata:
            labels:
              kyverno.io/createdBy: "{{request.userInfo.username}}"
