apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: qa2-security
  namespace: qa2
spec:
  rules:
  - name: runasnonroot
    match:
      any:
      - resources:
          kinds:
          - Pod
    mutate:
      patchesJson6902: |-
        - path: 
          op: 
          value: 