apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: mutate-pods
spec:
  rules:
  - name: add-imagepullsecret
    match:
      any:
      - resources:
          kinds:
          - Pod
    mutate:
      patchStrategicMerge:
        spec:
          imagePullSecrets:
          - name: somesecret
